version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist/frontend:/usr/share/nginx/html:ro
      
    restart: always
    depends_on:
      - backend

volumes:
  backend_node_modules:
    driver: local
